
CREATE TABLE IF NOT EXISTS ExpenseCategory(
id int AUTO_INCREMENT NOT NULL,
name VARCHAR(50) NOT NULL,
 PRIMARY KEY(id)
)

CREATE TABLE IF NOT EXISTS Expense(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
description VARCHAR(25) NOT NULL,
amount DOUBLE NOT NULL,
date VARCHAR(50) NOT NULL,
category_id int NOT NULL,
FOREIGN KEY(category_id) REFERENCES ExpenseCategory(id)
);

